### ISSUE TITLE
Punkteicons erstellen und mir bis Ende Juli 2016 schicken

### ISSUE THREAD

**Issue by sjlae** [sjlae/em2008#56]
Punkteicons für auf der 'Tipps erfassen' und 'Tipps Mitspieler' Seite. Folgende Punkteoptionen gibt es:
0 Punkte
1 Punkt
4 Punkte
5 Punkte
6 Punkte
8 Punkte
16 Punkte (High-Risk Volltreffer)

**Comment by gabac** [comment]
![16_points](https://cloud.githubusercontent.com/assets/50061/17473706/389f2f84-5d52-11e6-8d3d-d56101fe4157.png)
![8_points](https://cloud.githubusercontent.com/assets/50061/17473708/3a80fe22-5d52-11e6-8238-5a73cc0e661d.png)
![6_points](https://cloud.githubusercontent.com/assets/50061/17473710/3c75b984-5d52-11e6-8869-2f08f16a7ed1.png)
![5_points](https://cloud.githubusercontent.com/assets/50061/17473712/3e7190aa-5d52-11e6-990f-abeb51792921.png)
![4_points](https://cloud.githubusercontent.com/assets/50061/17473715/40b9be00-5d52-11e6-8939-5f299cefc147.png)
![1_points](https://cloud.githubusercontent.com/assets/50061/17473717/42dc4efa-5d52-11e6-9e46-bf8045dc5834.png)
![0_points](https://cloud.githubusercontent.com/assets/50061/17473721/44f25464-5d52-11e6-9c8b-c158ed3c3d72.png)

**Comment by gabac** [comment]
![new](https://cloud.githubusercontent.com/assets/50061/17479883/70bc23b8-5d75-11e6-8444-59ad0995e2a3.png)

**Comment by gabac** [comment]
![16_points](https://cloud.githubusercontent.com/assets/50061/17480393/01f80020-5d78-11e6-8478-ab372b51cd21.png)
![8_points](https://cloud.githubusercontent.com/assets/50061/17480397/01fe1d34-5d78-11e6-9c78-3095df002a5d.png)
![6_points](https://cloud.githubusercontent.com/assets/50061/17480398/0200c28c-5d78-11e6-99b7-4b7e9d6e14fd.png)
![5_points](https://cloud.githubusercontent.com/assets/50061/17480395/01f94a20-5d78-11e6-8cbe-0dd7cdf15d2e.png)
![4_points](https://cloud.githubusercontent.com/assets/50061/17480394/01f8ddf6-5d78-11e6-85a6-f78bd84c19b4.png)
![1_points](https://cloud.githubusercontent.com/assets/50061/17480396/01fd1fba-5d78-11e6-994e-144fb8641a82.png)
![0_points](https://cloud.githubusercontent.com/assets/50061/17480399/020e08fc-5d78-11e6-9581-ae716d7cc855.png)

**Comment by sjlae** [comment]
@gabac ich würd 0 und 1 nachli klarer vonenand underscheide. 8 und 16 würd ich diä glich farb näh, aber bi 16 s'icon suscht chli spezieller mache, was meinsch?

**Comment by gabac** [comment]
![0_points](https://cloud.githubusercontent.com/assets/50061/17480736/9663f27c-5d79-11e6-9b48-2d163def7334.png)
![16_points](https://cloud.githubusercontent.com/assets/50061/17480737/96756688-5d79-11e6-88a3-cfd27a539295.png)
![8_points](https://cloud.githubusercontent.com/assets/50061/17480738/9675bab6-5d79-11e6-8934-da3a9065d0bf.png)

**Comment by sjlae** [comment]
@gabac scho besser. :-) wasi nachli störend find, isch, dass de farbverlauf broche wird... zerscht schwarz und grau, dänn orange / bruun / rot und dänn wieder heller mit goldig...

**Comment by gabac** [comment]
ja bewuust, will das spezielle sind(eimal schlecht, eimal guet)

aber du findesches nöd guet?

**Comment by sjlae** [comment]
@gabac für 0, 1 und dänn zu 4 findis ok und verständlich... also vo ganz mies zu akzeptabel. aber vo 6 uf 8 würd ich de farbverlauf nöd namal bräche, sondern lah. und ebe, 16 söll identisch si vode farb, eifach suscht mit spezielle eigeschafte uffalle. was meinsch?

**Comment by gabac** [comment]
also 0,1 loh.

und denne 4,5,6,8 die glich farb oder die glich farb aber en verlauf?

16 hani ja scho speziell well zahl farbig isch und de ring au oder wetsch es nho spezieller?

**Comment by sjlae** [comment]
@gabac  4,5,6 und 8 nöd diä glich farb, aber am farbverlauf entsprechend. also entweder immer heller oder immer dünkler, aber nöd zerscht dünkler und dänn für 8 plötzlich wieder andersch. fürs 16 chöntisch ja viellicht na öpis zuesätzlichs mache, wiä zum bsp. es chrönli obe druf...

**Comment by gabac** [comment]
![points_16](https://cloud.githubusercontent.com/assets/50061/17689214/50f570ea-6386-11e6-8578-8b9120f1898b.png)
![points_8](https://cloud.githubusercontent.com/assets/50061/17689216/50f60596-6386-11e6-8931-a8472ee41fa9.png)
![points_6](https://cloud.githubusercontent.com/assets/50061/17689217/50f629cc-6386-11e6-9d42-33e9a393e32c.png)
![points_5](https://cloud.githubusercontent.com/assets/50061/17689218/50f66126-6386-11e6-9b6e-ad4aadeb4609.png)
![points_4](https://cloud.githubusercontent.com/assets/50061/17689215/50f5e2b4-6386-11e6-8676-697e75db3383.png)

**Comment by gabac** [comment]
![points_8](https://cloud.githubusercontent.com/assets/50061/17772836/489a0016-654b-11e6-9093-0c86a998d2bd.png)

**Comment by sjlae** [comment]
@gabac hey cüüüril, jetzt hani endli diä neue icons mal ibaut. gseht super us. nur zwei sache hani na azfüege. :-) 1. chöntisch echt bim 16-punkt icon de chreis glich gross mache, wiä bi allne andere icons? 2. d'farb vode 0 und 1 punkt-icons muesch ändere, diä gseht mer uf eusem hindergrund fascht nöd. merci viel mal.
