### ISSUE TITLE
Meldungen auf neues Layout ändern

### ISSUE THREAD

**Issue by sjlae** [sjlae/em2008#58]
Meldungen auf neues Layout ändern --> aktuell erscheinen noch die alten Warn-, Bestätigungs- und Errormeldungen.

**Comment by gabac** [comment]
Sieht noch schlecht für Seiten mit Tabs aus

**Comment by sjlae** [comment]
@gabac Wenn ich auf dem Tab 'Weitere Tipps' zwei Mal das gleiche Team erfasse und auf Speichern klicke, dann springe ich auf den ersten Tab. Dort erscheint zwar die Fehlermeldung, nicht aber auf dem Tab 'Weitere Tipps'. Also eigentlich zwei Probleme, 1. springe ich auf den ersten Tab und 2. wird die Meldung auf dem 'Weitere Tipps' Tab nicht gezeigt, wenn ich dorthin klicke.

**Comment by sjlae** [comment]
@gabac - du verschiebst die Meldungen (Bestätigung und Fehler) noch etwas nach oben, damit der Abstand zwischen Bild und Meldung nicht so gross ist.

Ich schaue, wie sich das Tab- und Messageverhalten in der alten Version verhalten hat.
